kotlinVersion = 1.9.20
kotlinMultiplatformVersion = 1.5.31
kotlinxSerializationVersion = 1.3.1
microutilsLoggingVersion = 2.1.23
shadowPluginVersion = 6.1.0
licenseVersion = 0.16.1
logbackVersion =  1.2.12
psxpaulExecforkVersion = 0.2.2

drillCiCdIntegrationVersion = 0.1.12-alpha.3
drillTestAgentVersion = 0.23.9
drillAppAgentVersion = 0.9.11

org.gradle.jvmargs = -Xmx1024m  -XX:MaxMetaspaceSize=1024m
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.workers.max = 4
