kotlinVersion = 2.3.10
kotlinxSerializationVersion = 1.10.0
microutilsLoggingVersion = 2.1.23
shadowPluginVersion = 6.1.0
licenseVersion = 0.16.1
logbackVersion =  1.2.12
psxpaulExecforkVersion = 0.2.2

drillCiCdIntegrationVersion = 0.10.0
drillAgentVersion = 0.10.0
drillAgentMode = NATIVE

org.gradle.jvmargs = -Xmx1024m  -XX:MaxMetaspaceSize=1024m
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.workers.max = 4
org.gradle.java.installations.auto-download=true
