name: Tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System (ubuntu-latest, windows-latest, macos-latest)'
        required: true
        default: 'ubuntu-latest'
      java:
        description: 'Java version (8, 11, 17, 21)'
        required: true
        default: '17'
      skipTests:
        description: 'Skip tests (websockets, test-frameworks, ...)'
        required: false
      agentMode:
        description: 'Agent mode (NATIVE, JAVA)'
        required: false
        default: 'NATIVE'
      appAgentVersion:
        description: 'Drill AppAgent version (0.9.17)'
        required: false
        default: '0.9.17'
      testAgentVersion:
        description: 'Drill TestAgent version (0.23.10)'
        required: false
        default: '0.23.10'
jobs:
  tests:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17.0
          distribution: corretto

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up Gradle Wrapper
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests using Gradle Wrapper
        run: ./gradlew test -PjavaVersion=${{ github.event.inputs.java }} --info

      - name: Test Report (Linux)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: startsWith(github.event.inputs.os, 'ubuntu-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests/**/build/test-results/test/TEST-*.xml

      - name: Test Report (Windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: startsWith(github.event.inputs.os, 'windows-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests\**\build\test-results\test\TEST-*.xml                      

      - name: Test Report (MacOS)
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: startsWith(github.event.inputs.os, 'macos-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests/**/build/test-results/test/TEST-*.xml

#      - name: Upload aggregated test report
#        uses: actions/upload-artifact@v4
#        if: success() || failure()
#        with:
#          name: aggregated-results-${{ matrix.os }}-java${{ matrix.java-version }}
#          path: build/reports/tests/unit-test/aggregated-results/
